try {
    throw new Error('Something went wrong!');
} catch {
    console.log('Caught an error');
}