В JavaScript, при использовании async/await, обработка исключений осуществляется с помощью конструкции 
try...catch. Это позволяет вам обрабатывать ошибки, возникающие в асинхронных функциях, так же, как вы бы делали это в синхронном коде.